<div>
    <a href="/owner/maisons">🔙 Retour</a>
</div>
<h1><?php printf('Maison : %s - %s', $maison->getId(), $maison->getLabel()) ?></h1>
<h2>Modifier</h2>
<form action="<?php printf('/owner/maisons/%s', $maison->getId()) ?>" method="post" novalidate>
    <div>
        <label for="input-label">Label :</label>
        <input type="text" name="label" id="input-label" value="<?php echo $maison->getLabel() ?>">
    </div>
    <div>
        <label for="input-seats">Places assises :</label>
        <input type="number" name="seats" id="input-seats" value="<?php echo $maison->getSeats() ?>">
    </div>
    <div>
        <label for="select-energy">Motorisation :</label>
        <select name="energy" id="select-energy">
            <option value="">Choisissez...</option>
            <!-- TODO: La boucle qui remonte les vraies motorisations -->
            <option value="1" selected>Essence</option>
        </select>
    </div>
    <div>
        <label for="input-plate_number">Numéro d'immatriculation :</label>
        <input type="text" name="plate_number" id="input-plate_number" value="<?php echo $maison->getPlateNumber() ?>">
    </div>
    <div>
        <label for="input-price_day">Prix par jour :</label>
        <input type="number" name="price_day" id="input-price_day" value="<?php echo $maison->getPriceDay() ?>">
    </div>
    <div>
        <label for="input-price_distance">Prix du kilomètre supplémentaire :</label>
        <input type="number" name="price_distance" id="input-price_distance" value="<?php echo $maison->getPriceDistance() ?>">
    </div>
    <div>
        <label for="input-image">Image :</label>
        <!-- TODO: Gérer l'upload d'image avec un input de type "file" -->
        <input type="text" name="image" id="input-image" value="<?php echo $maison->getImage() ?>">
    </div>
    <fieldset>
        <legend>Logements</legend>
        <?php
        foreach ($logements as $logement) {
            echo '<div>';
            printf(
                '<input type="checkbox" name="logements[]" id="chk-logement-%1$s" value="%1$s"%2$s> ',
                $logement->getId(),
                in_array($logement->getId(), $maison_logements_ids) ? ' checked' : ''
            );
            printf('<label for="chk-logement-%s">%s</label>', $logement->getId(), $logement->getLabel());
            echo '</div>';
        }
        ?>
    </fieldset>
    <div>
        <input type="submit" value="Enregistrer la modification">
    </div>
</form>
<div>
    <a href="<?php printf('/owner/maisons/%s/delete', $maison->getId()) ?>">❌ Supprimer</a>
</div>