<div>
    <a href="/owner">🏠 Retour</a>
</div>
<h1>Voitures</h1>
<p>
    <a href="/owner/maisons/add">Ajouter une voiture</a>
</p>
<?php if( !empty($maisons) ): ?>
<ul>
    <?php foreach( $maisons as $maison ): ?>
        <li><?php printf( '<a href="/owner/maisons/%1$s">%1$s - %2$s</a>', $maison->getId(), $maison->getLabel() ) ?></li>
    <?php endforeach ?>
</ul>
<?php else: ?>
    <div>Aucune Maison de définie.</div>
<?php endif ?>