<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Se connecter</title>
    <link rel="stylesheet" href="styles.css">
</head>

<body>
    <div class="form-container">
        <h1>Se connecter</h1>
        <form action="home.phmtl" method="POST">
            <!-- Email -->
            <label for="email">Email</label>
            <input type="email" id="email" name="email" maxlength="255" required placeholder="Votre adresse email">

            <!-- Mot de passe -->
            <label for="password">Mot de passe</label>
            <input type="password" id="password" name="password" maxlength="255" required placeholder="Votre mot de passe">

            <!-- Bouton d'inscription -->
            <button type="submit" class="btn btn-primary">Créer mon compte</button>
        </form>
    </div>
</body>

</html>