<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Site dédié à la location de logements .">
    <link href="../assets/style.css" rel="stylesheet">

    <header>
        <!-- Texte du nom CAZ KEN, centré -->

        <div class="container_title">
            <h1>
                <a href="/">CAZ KEN</a>
            </h1>
        </div>

        <!-- Conteneur pour les boutons à droite -->
        <div class="button_container">
            <!-- Premier bouton -->


            <!-- Premier bouton -->

            <a href="/ajoutAnnonce"><button class="button">Ajouter une annonce</button></a>

            <!-- Premier bouton -->
            <button class="button">
                Votre Profil
            </button>

            <!-- Deuxième bouton -->
            <button class="button">
                Se deconnecter
            </button>
        </div>



        </div>
    </header>
    <!DOCTYPE html>
    <html lang="fr">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="Site dédié à la location de logements .">
        <link href="../assets/style.css" rel="stylesheet">

        <header>
            <!-- Texte du nom CAZ KEN, centré -->

            <div class="container_title">
                <h1>
                    <a href="/">CAZ KEN</a>
                </h1>
            </div>

            <!-- Conteneur pour les boutons à droite -->
            <div class="button_container">
                <!-- Premier bouton -->


                <!-- Premier bouton -->

                <a href="/ajoutAnnonce"><button class="button">Ajouter une annonce</button></a>

                <!-- Premier bouton -->
                <button class="button">
                    Votre Profil
                </button>

                <!-- Deuxième bouton -->
                <button class="button">
                    Se deconnecter
                </button>
            </div>



            </div>
        </header>