<h1> Salut beaux site</h1>
<!-- Section des hébergements 
    <section class="listings">
        <h2>Nos Hébergements </h2>
        <div class="cards">
            <div class="card">
                <img src="https://via.placeholder.com/300" alt="Hébergement">
                <h3>Villa au bord de la mer</h3>
                <p>À partir de 120€/nuit</p>
            </div>

            <div class="card">
                <img src="https://via.placeholder.com/300" alt="Hébergement">
                <h3>Appartement cosy en ville</h3>
                <p>À partir de 80€/nuit</p>
            </div>
            <div class="card">
                <img src="https://via.placeholder.com/300" alt="Hébergement">
                <h3>Chalet en montagne</h3>
                <p>À partir de 150€/nuit</p>
            </div>
        </div>
    </section>