<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Site Airbnb</title>
    <link rel="stylesheet" href="styles.css">
</head>

<body>
    <!-- Barre de navigation -->
    <header class="navbar">
        <div class="logo">CAZ KEN</div>
        <div class="nav-buttons">
            <button class="btn btn-outline">Connexion</button>
            <a href="../user/create-account.phtml" class="btn">Se connecter</a>
        </div>
    </header>