<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Site Airbnb</title>
    <link rel="stylesheet" href="styles.css">
</head>

<body>
    <!-- Barre de navigation -->
    <header class="navbar">
        <div class="logo">CAZ KEN</div>
        <div class="nav-buttons">
            <a href="/connect" class="btn">Se connecter</a>
            <a href="/create-account" class="btn">S'Enregistrer</a>
        </div>
        <div class="home-icon">
            <a href="home.phtml" class="home-button">
                <span class="home-icon">&#x2302;</span> <!-- Symbole de la maison -->
            </a>
        </div>
    </header>