<?php
// Assurez-vous que l'utilisateur est un propriétaire
//session_start();
//if ($_SESSION['role'] != '1') { // Vérifie si l'utilisateur est un "Owner"
//   header("Location: /login.php"); // Redirige vers la page de connexion si ce n'est pas un propriétaire
//   exit();
//}
?>

<body>


    <div class="owner-main-content">
        <div class="owner-dashboard">
            <h2 class="h2owner">Bienvenue, Propriétaire!</h2>
            <p class="phowner">Gérez vos annonces, modifiez les informations et consultez vos statistiques.</p>

            <div class="actionsowner">
                <a href="create_announce.php" class="btn">Créer une nouvelle annonce</a>
                <a href="manage_announces.php" class="btn">Gérer mes annonces</a>
                <a href="view_statistics.php" class="btn">Consulter mes anciennes annonces</a>
            </div>
        </div>
    </div>

</body>