<?php

use App\Controller\PageController;
?>

<body>


    <div class="owner-main-content">
        <div class="owner-dashboard">
            <h2 class="h2owner">Bienvenue, Propriétaire!</h2>
            <p class="phowner">Gérez vos annonces, modifiez les informations et consultez vos statistiques.</p>

            <div class="actionsowner">
                <a href="/owner/createannounce" class="btn btn-primary">Créer une annonce</a>
                <a href="/owner/manageannounce" class="btn">Gérer mes annonces</a>
                <a href="/owner/oldannounce" class="btn">Consulter mes anciennes annonces</a>
            </div>
        </div>
    </div>

</body>