<body>
    <div class="annoucement-container">
        <?php if (!empty($announcements)) : ?>
            <ul>
                <?php var_dump($announcements);
                foreach ($announcements as $annoucement): { ?>
                        <div class="$annoucement">
                            <ul>
                                <h3 class="titre"><u><?php echo $annoucement->getTitre() ?></u></h3>
                                <h4><u>Description :</u> <?php echo $annoucement->getDescription() ?></h4>
                                <h4><u>Propriétaire :</u> <?php echo $annoucement->getAllName() ?></h4>
                                <li><u>Surface :</u> <?php echo $annoucement->getTaille() ?> m²</li>
                                <li><u>Nombre de chambre(s) :</u> <?php echo $annoucement->getSleeping() ?> Chambre</li>
                                <li><u>Adresse :</u> <?php echo $annoucement->getAdressComplete() ?></li>
                                <li><u>Prix par nuit :</u> <?php echo $annoucement->getPrice() ?> €</li>
                                <li><u>Type de logement :</u> <?php echo $annoucement->getLabelComplete() ?></li>
                                <li><u>Equipements disponibles :</u> <?php echo $annoucement->getLabelComplete() ?></li>
                            </ul>
                        <?php } ?>
                        </div>
                    <?php endforeach ?>
            </ul>
    </div>
<?php else: ?>
    <div>Aucune location enregistrée</div>
<?php endif ?>
</body>