    <div class="card">
        <div class="card-body">
            <!-- Nom du logement -->
            <h5 class="card-title">Nom du logement : <?php htmlspecialchars($name) ?></h5>

            <!-- Prix -->
            <p class="card-text"><strong>Prix :</strong> <?php number_format($price, 2, ',', ' ') ?> €</p>

            <!-- Type de logement -->
            <p class="card-text"><strong>Type :</strong>
                <?php ($type_logement == 1 ? "Logement entier" : ($type_logement == 2 ? "Chambre privée" : "Chambre partagée")) ?>
            </p>

            <!-- Taille -->($taille) ?> m²</p>

            <!-- Description -->
            <p class="card-text"><strong>Description :</strong><br> <?php nl2br(htmlspecialchars($description)) ?></p>

            <!-- Nombre de chambres -->
            <p class="card-text"><strong>Nombre de chambres :</strong> <?php htmlspecialchars($bedrooms) ?></p>
        </div>
    </div>

    </body>

    </html>