<div>
    <a href="/owner">🏠 Retour</a>
</div>
<h1>Voitures</h1>
<p>
    <a href="/owner/logements/add">Ajouter une voiture</a>
</p>
<?php if( !empty($logements) ): ?>
<ul>
    <?php foreach( $logements as $logement ): ?>
        <li><?php printf( '<a href="/owner/logements/%1$s">%1$s - %2$s</a>', $logement->getId(), $logement->getLabel() ) ?></li>
    <?php endforeach ?>
</ul>
<?php else: ?>
    <div>Aucune voiture définie.</div>
<?php endif ?>