<div>
    <a href="/owner">🏠 Retour</a>
</div>
<h1>Logements</h1>
<p>
    <a href="/owner/logements/add">Ajouter une Logement</a>
</p>
<?php if( !empty($logements) ): ?>
<ul>
    <?php foreach( $logements as $category ): ?>
        <li><?php printf( '<a href="/owner/logements/%1$s">%1$s - %2$s</a>', $category->getId(), $category->getLabel() ) ?></li>
    <?php endforeach ?>
</ul>
<?php else: ?>
    <div>Aucune Logement définie.</div>
<?php endif ?>