<div>
    <a href="/owner">🏠 Retour</a>
</div>
<h1>Voitures</h1>
<p>
    <a href="/owner/cars/add">Ajouter une voiture</a>
</p>
<?php if( !empty($cars) ): ?>
<ul>
    <?php foreach( $cars as $car ): ?>
        <li><?php printf( '<a href="/owner/cars/%1$s">%1$s - %2$s</a>', $car->getId(), $car->getLabel() ) ?></li>
    <?php endforeach ?>
</ul>
<?php else: ?>
    <div>Aucune voiture définie.</div>
<?php endif ?>